### ISSUE TITLE
Security issue: user should not be allowed to register without a strong password

### ISSUE THREAD

**Issue by muskaancontlo** [0xfoo/django-todolist#31]
Enable users to choose only strong passwords with the following criteria
1. Atleast 8 characters long
2. Having atleast 1 uppercase letter
3. Having atleast 1 lowercase letter
4. Having atleast 1 digit

**Comment by rtzll** [comment]
This can be configured using [AUTH_PASSWORD_VALIDATORS](https://docs.djangoproject.com/en/5.0/topics/auth/passwords/#enabling-password-validation)
